apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: gemini-diagram-mcp
spec:
  hosts:
    - diagram.arunlabs.com
  gateways:
    - istio-system/arunlabs-public-gateway
  http:
    - route:
        - destination:
            host: gemini-diagram-mcp.llm-infra.svc.cluster.local
            port:
              number: 3000
